server:
  port: 9000

management:
  endpoints:
    web:
      base-path: "/olx-login-monitor"
      exposure:
        include: "*"

spring:
  application:
    name: login-service
  zipkin:
    base-url: http://localhost:9411
  config:
    import: configserver:http://localhost:8888