server:
  port: 9000

management:
  endpoints:
    web:
      base-path: "/olx-login-monitor"
      exposure:
        include: "*"

spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://localhost:3306/olx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true